version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:clientes;DB_CLOSE_DELAY=-1
    depends_on:
      - h2-server

  h2-server:
    image: oscarfonts/h2
    ports:
      - "8082:8082"